version: "3.9"

services:
  postgres:
    image: postgres:17
    restart: always
    env_file:
      - .env
    container_name: Firmeza-Postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - firmeza-network

  tests:
    build:
      context: .
      dockerfile: Firmeza.Test/Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};
    depends_on:
      - postgres
    command: [ "dotnet", "test", "--logger:trx" ]
    networks:
      - firmeza-network

  api:
    build:
      context: .
      dockerfile: Firmeza.WebApi/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RUN_MIGRATIONS=true
      - RUN_SEEDERS=1
      - ConnectionStrings__Default=Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};
      - DB_CONNECTION=Server=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};
    depends_on:
      - postgres
    ports:
      - "5000:8080"
    networks:
      - firmeza-network

  admin:
    build:
      context: .
      dockerfile: AdminDashboard.Web/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};
      - DB_CONNECTION=Server=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};
    depends_on:
      - api
    ports:
      - "5001:8080"
    networks:
      - firmeza-network

  front-end:
    build:
      context: Front-end
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_ADMIN_DASHBOARD_URL: ${VITE_ADMIN_DASHBOARD_URL}
    depends_on:
      - api
    ports:
      - "5173:80"
    networks:
      - firmeza-network

volumes:
  dbdata:


networks:
  firmeza-network:
    driver: bridge
